name: 'Full Service Deploy'
description: 'Checks out code, gets commit SHA, optionally tags, builds image and deploys to ECS'

inputs:
  # Checkout
  ref:
    required: false
    default: ''
    description: 'Git ref to checkout (branch, commit, tag). default is the current SHA'

  # Build
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: 'Dockerfile'
  context:
    description: 'Docker context for the build'
    required: false
    default: '.'
  repository:
    description: 'ECR repository name'
    required: true
  environment:
    description: 'Environment to deploy (staging or production)'
    required: true
  create-tag:
    description: 'Create a tag for the service with the date/time (ex: when deploying to prod)'
    required: false
    default: 'false'
  sentry-auth-token:
    description: 'Sentry auth token (optional)'
    required: false
  force-build:
    description: 'Whether to force the build if the image already exists'
    type: boolean
    default: false

  builder:
    description: 'Name of the builder to use: docker (default), depot'
    required: false
    default: 'docker'
  depot-project:
    description: 'Depot project name.'
    required: false
    default: ''

  # Deploy
  service:
    description: 'Name of the ECS service to deploy (must be in services.json in the repository)'
    required: true
  role-ecs-update:
    description: 'Role for the ECS update (skynet_infra_update, sauron_infra_update, realtime_infra_update)'
    required: true
  skip-ecs-update:
    description: 'Build, tag and push the image, but skip updating the ECS services'
    required: false
    default: 'false'
  target:
    description: 'Deployment Target (main=default image, blue=blue env, green=green env, all=update all)'
    required: false
    default: 'main'

outputs:
  sha:
    description: 'Checked out commit SHA'
    value: ${{ steps.commit.outputs.sha }}

runs:
  using: 'composite'
  steps:
    - name: Print all inputs
      run: |
        echo "::group::Inputs"
        echo "ref=${{ inputs.ref }}"
        echo "resolvedRef=${{ inputs.ref != '' && inputs.ref || github.sha }}"
        echo "dockerfile=${{ inputs.dockerfile }}"
        echo "context=${{ inputs.context }}"
        echo "repository=${{ inputs.repository }}"
        echo "environment=${{ inputs.environment }}"
        echo "create-tag=${{ inputs['create-tag'] }}"
        echo "sentry-auth-token=${{ inputs['sentry-auth-token'] }}"
        echo "builder=${{ inputs.builder }}"
        echo "depot-project=${{ inputs['depot-project'] }}"
        echo "service=${{ inputs.service }}"
        echo "role-ecs-update=${{ inputs['role-ecs-update'] }}"
        echo "skip-ecs-update=${{ inputs['skip-ecs-update'] }}"
        echo "::endgroup::"
      shell: bash

    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref != '' && inputs.ref || github.sha }}

    - name: Get checked out commit SHA
      id: commit
      run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Deployment Information
      id: deployment-info
      run: |
        SHA_SHORT=$(echo "${{ steps.commit.outputs.sha }}" | cut -c1-8)
        echo "BUILD_START=$(date +%s)" >> "$GITHUB_OUTPUT"
        echo "SHA_SHORT=${SHA_SHORT}" >> "$GITHUB_OUTPUT"

        REF_INPUT="${{ inputs.ref }}"
        if [ -n "$REF_INPUT" ]; then
          REF_ROW="| Ref | \`${REF_INPUT}\` |"
        else
          REF_ROW=""
        fi

        {
          echo ""
          echo "| Property | Value |"
          echo "|----------|-------|"
          if [ -n "$REF_ROW" ]; then
            echo "$REF_ROW"
          fi
          echo "| Commit | [\`${SHA_SHORT}\`](https://github.com/${{ github.repository }}/commit/${{ steps.commit.outputs.sha }}) |" >> "$GITHUB_STEP_SUMMARY"
          echo "| Target | \`${{ inputs.target }}\` |"
          echo "| Builder | \`${{ inputs.builder }}\` |"
        } >> "$GITHUB_STEP_SUMMARY"
      shell: bash

    - name: Create and push service tag
      if: ${{ inputs.create-tag == 'true' }}
      run: |
        export TZ="America/New_York"
        tag_name="${{ inputs.service }}-$(date +"%Y-%m-%d_%H-%M-%S")"
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag "$tag_name" "${{ steps.commit.outputs.sha }}"
        git push origin "$tag_name"
      shell: bash

    - name: Build and Push Image (Docker)
      if: ${{ inputs.builder == 'docker' }}
      id: build-docker
      uses: botpress/gh-actions/build/docker@v3.1
      with:
        dockerfile: ${{ inputs.dockerfile }}
        repository: ${{ inputs.repository }}
        context: ${{ inputs.context }}
        tag: ${{ steps.commit.outputs.sha }}
        force: ${{ inputs.force-build }}
        sentry-auth-token: ${{ inputs.sentry-auth-token }}
        push: true

    - name: Build and Push Image (Depot)
      if: ${{ inputs.builder == 'depot' }}
      id: build-depot
      uses: botpress/gh-actions/build/depot@v3.1
      with:
        dockerfile: ${{ inputs.dockerfile }}
        repository: ${{ inputs.repository }}
        context: ${{ inputs.context }}
        tag: ${{ steps.commit.outputs.sha }}
        sentry-auth-token: ${{ inputs.sentry-auth-token }}
        depot-project: ${{ inputs.depot-project }}
        push: true

    - name: Build Summary
      id: build-summary
      run: |
        BUILD_END=$(date +%s)
        BUILD_DURATION=$((BUILD_END - "${{ steps.deployment-info.outputs.BUILD_START }}"))

        format_duration() {
          local total_seconds=$1
          local minutes=$((total_seconds / 60))
          local seconds=$((total_seconds % 60))
          if [ $minutes -gt 0 ]; then
            echo "${minutes}m ${seconds}s"
          else
            echo "${seconds}s"
          fi
        }

        BUILD_FORMATTED=$(format_duration "$BUILD_DURATION")

        echo "" >> "$GITHUB_STEP_SUMMARY"
        echo "**Build:** ${BUILD_FORMATTED} ✅" >> "$GITHUB_STEP_SUMMARY"
      shell: bash

    - name: Deploy to ECS
      id: deploy
      uses: botpress/gh-actions/tag-and-deploy@v3.3
      with:
        service: ${{ inputs.service }}
        role-ecs-update: ${{ inputs.role-ecs-update }}
        image-tag: ${{ steps.commit.outputs.sha }}
        environment: ${{ inputs.environment }}
        skip-ecs-update: ${{ inputs.skip-ecs-update }}
        target: ${{ inputs.target }}
