name: 'get_release_details'
description: 'Returns release details like the latest release tag (ignore branches) and a changelog'
inputs:
  path:
    description: 'Custom path to package.json'
    required: false
  token:
    description: 'Github Token'
    required: false
    default: ${{ github.token }}
  mode:
    description: 'Check wether the "version" should be the same as the "tag" or the opposite'
    required: false
    default: 'version'
outputs:
  latest_tag:
    description: 'Latest Release Tag'
  version:
    description: 'The version in package.json'
  changelog:
    description: 'Contains the changelog since the last release tag'
  is_new_release:
    description: "Return true if the last release tag doesn't match the package.json version"
runs:
  using: 'node12'
  main: 'dist/index.js'
