name: 'get_release_details'
description: 'Returns the latest release tag (ignore branches)'
inputs:
  path:
    description: 'Custom path to package.json'
    required: false
outputs:
  latest_tag:
    description: 'Latest Release Tag'
  version:
    description: 'The version in package.json'
  changelog:
    description: 'Contains the changelog since the last release tag'
  is_new_release:
    description: 'Return true if the last release tag doesnt match the package.json version'
runs:
  using: 'node12'
  main: 'dist/index.js'
