name: Check GitHub Actions Scripts
description: Check shell scripts in GitHub Actions workflows and actions

inputs:
  check_scripts:
    type: boolean
    required: false
    default: true
  scripts_dir:
    type: string
    required: false
    default: .
  check_actions:
    type: boolean
    required: false
    default: true
  actions_dir:
    type: string
    required: false
    default: .github/actions
  check_workflows:
    type: boolean
    required: false
    default: true
  workflows_dir:
    type: string
    required: false
    default: .github/workflows

runs:
  using: composite
  steps:
    - name: Install shellcheck
      shell: bash
      run: |
        echo "::group::Installing shellcheck"
        sudo apt update
        sudo apt install -y shellcheck
        echo "::endgroup::"
        shellcheck --version

    - name: Install yq
      shell: bash
      run: |
        echo "::group::Installing yq"
        sudo apt install -y wget
        VERSION="v4.52.2"
        PLATFORM="linux_amd64"
        wget -qO- https://github.com/mikefarah/yq/releases/download/${VERSION}/yq_${PLATFORM}.tar.gz | tar xz && sudo mv yq_${PLATFORM} /usr/local/bin/yq
        echo "::endgroup::"
        yq --version

    - name: Checks
      shell: bash
      run: |
        CHECK_SCRIPTS="${{ inputs.check_scripts }}"
        CHECK_ACTIONS="${{ inputs.check_actions }}"
        CHECK_WORKFLOWS="${{ inputs.check_workflows }}"

        SUCCESS=true

        if [ "$CHECK_SCRIPTS" = "true" ]; then
          "$GITHUB_ACTION_PATH/check-scripts.sh" "${{ inputs.scripts_dir }}" || SUCCESS=false
        fi
        if [ "$CHECK_ACTIONS" = "true" ]; then
          "$GITHUB_ACTION_PATH/check-actions.sh" "${{ inputs.actions_dir }}" || SUCCESS=false
        fi
        if [ "$CHECK_WORKFLOWS" = "true" ]; then
          "$GITHUB_ACTION_PATH/check-workflows.sh" "${{ inputs.workflows_dir }}" || SUCCESS=false
        fi

        if [ "$SUCCESS" = "false" ]; then
          exit 1
        fi
