name: Check GitHub Actions Scripts
description: Check shell scripts in GitHub Actions workflows and actions

inputs:
  check_scripts:
    type: boolean
    required: false
    default: true
  check_actions:
    type: boolean
    required: false
    default: true
  check_workflows:
    type: boolean
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Install shellcheck and yq
      shell: bash
      run: |
        echo "::group::Installing shellcheck and yq"
        sudo apt update
        sudo apt install -y shellcheck yq jq
        echo "::endgroup::"
        shellcheck --version
        yq --version
        jq --version

    - name: Checks
      shell: bash
      run: |
        CHECK_SCRIPTS="${{ inputs.check_scripts }}"
        CHECK_ACTIONS="${{ inputs.check_actions }}"
        CHECK_WORKFLOWS="${{ inputs.check_workflows }}"

        SUCCESS=true

        if [ "$CHECK_SCRIPTS" = "true" ]; then
          "$GITHUB_ACTION_PATH/check-scripts.sh" || SUCCESS=false
        fi
        if [ "$CHECK_ACTIONS" = "true" ]; then
          "$GITHUB_ACTION_PATH/check-actions.sh" || SUCCESS=false
        fi
        if [ "$CHECK_WORKFLOWS" = "true" ]; then
          "$GITHUB_ACTION_PATH/check-workflows.sh" || SUCCESS=false
        fi

        if [ "$SUCCESS" = "false" ]; then
          exit 1
        fi
