name: Publish If Not Exists
description: Publishes a local package if it doesn't already exist on NPM Registry

inputs:
  path:
    description: Path to the package to publish
    required: true

  token:
    description: NPM access token
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install JQ
      shell: bash
      run: sudo apt-get install jq
    - name: Login
      shell: bash
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.token }}" > ~/.npmrc
    - name: Publish
      shell: bash
      run: |
        file_content=$(cat ${{ inputs.path }}/package.json)

        name=$(echo $file_content | jq -r ".name")
        version=$(echo $file_content | jq -r ".version")

        echo "name: $name"
        echo "version: $version"

        package_ref="$name@$version"
        if npm view $package_ref > /dev/null 2>&1 ; then
          echo "Package $package_ref already published"
          exit 0
        fi

        echo "Publishing version $package_ref"
        cd ${{ inputs.path }} && npm publish --access public
