name: AWS S3 Files
description: Deploy files to an s3 bucket
inputs:
  source:
    description: "source directory to upload into the s3 bucket"
    required: true
    default: "./dist"
  bucket:
    description: bucket name to deploy to
    required: true
  prefix:
    description: "prefix where to upload files in bucket"
    default: ""
    required: true
  aws-role:
    description: "aws role name"
    required: true
  aws-region:
    description: "aws region"
    required: true
    default: us-east-1
  invalidate-cloudfront: 
    description: "invalidate cloudfront distribution"
    required: true
    default: "false"
  cloudfront-distribution:
    description: "cloudfront distribution id"

runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-session-name: s3_upload
        role-to-assume: ${{ inputs.aws-role }}
        aws-region: ${{ inputs.aws-region }}
    - name: Deploy files to S3 bucket
      shell: bash
      run: aws s3 sync ${{ inputs.source }} s3://${{ inputs.bucket }}/${{ inputs.prefix }} --delete
    - name: Invalidate Cloudfront
      if: ${{ inputs.invalidate-cloudfront }}
      shell: bash
      run: aws cloudfront create-invalidation --distribution-id ${{ inputs.cloudfront-distribution }} --paths '/*';
