name: Check GitHub Actions Scripts
description: Check shell scripts in GitHub Actions workflows and actions

runs:
  using: 'composite'
  steps:
    - name: Install yq and shellcheck
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y yq shellcheck

    - name: Check scripts
      shell: bash
      run: ./check-scripts.sh

    - name: Check actions
      shell: bash
      run: ./check-actions.sh

    - name: Check workflows
      shell: bash
      run: ./check-workflows.sh