name: 'fetch_release_changelogs'
description: 'Returns the release changelog of some repositories'
inputs:
  repos:
    description: 'The list of repos to retrieve changelogs from (must be valid JSON)'
    required: true
  token:
    description: 'Github Token'
    required: false
    default: ${{ github.token }}
outputs:
  changelog:
    description: 'Contains all the changelogs'
runs:
  using: 'node12'
  main: 'dist/index.js'
