name: Release
on:
  workflow_dispatch:
    inputs:
      tag-name:
        required: true
        description: Tag name to push (e.g., v1.2.3)
      force:
        required: false
        default: 'false'
        type: boolean
        description: Force push the tag if it already exists

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create and push tag
        env:
          TAG_NAME: ${{ inputs.tag-name }}
          FORCE_PUSH: ${{ inputs.force }}
        run: |
          git tag -f "$TAG_NAME"

          if [ "$FORCE_PUSH" = "true" ]; then
            git push origin "$TAG_NAME" --force
          else
            git push origin "$TAG_NAME"
          fi
