name: Release
on:
  workflow_dispatch:
    inputs:
      tag-name:
        required: true
        description: tag name to push
jobs:
  release:
    name: Release
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      #- uses: actions/setup-node@v2
      #  with:
      #    node-version: '12.18.1'
      #    cache: 'yarn'

      #- name: Fetch Node Packages
      #  run: |
      #    yarn --immutable

      #- name: Build Actions
      #  run: yarn build

      - name: Push Release
        shell: bash
        run: |
          .github/workflows/code/release.sh
        env:
          TAG_NAME: ${{ github.event.inputs.tag-name }}
