name: Tests
on: [pull_request]
jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Fetch Node Packages
        run: |
          yarn --immutable
      - name: Run tests
        run: |
          yarn test --coverage --verbose

  get_release_details:
    name: Test Get Release Details
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Get Release Details
        id: release_details
        uses: ./get_release_details

      - name: Change Log
        env:
          CHANGELOG: ${{ steps.release_details.outputs.changelog }}
          IS_NEW_RELEASE: ${{ steps.release_details.outputs.is_new_release }}
          VERSION: ${{ steps.release_details.outputs.version }}
          LATEST_TAG: ${{ steps.release_details.outputs.latest_tag }}
        run: |
          printf 'Changelog:\n%s\n' "$CHANGELOG"
          echo "Is new release?: $IS_NEW_RELEASE"
          echo "Version: $VERSION"
          echo "Latest Tag: $LATEST_TAG"
